Problem 1

In [ ]:
#Name:Shreya Bhatta
#Un Id:2408994

Problem 1

In [1]:
#Task1
import numpy as np
empty_arr = np.zeros((2,2))
print(empty_arr)

[[0. 0.]
 [0. 0.]]


In [2]:
#Task2
empty_Arr2=np.zeros((4,2))
print(empty_Arr2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
#TAsk3
array_full=np.full(2,2)
print(array_full)

[2 2]


In [4]:
#Task4
zeros_arr= np.zeros([2,2])
print(zeros_arr)

[[0. 0.]
 [0. 0.]]


In [34]:
#TAsk5
ones_Arr=np.ones([2,2])
print(ones_Arr)

[[1. 1.]
 [1. 1.]]


In [6]:
#TAsk6
new_list=[1,2,3,4]
array = np.array(new_list)
print(array)

[1 2 3 4]


Problem2

In [7]:
#Task1
array_2 = np.arange(10,50)
print(array_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#Task2
array_3 = np.array([0,1,2,3,4,5,6,7,8])
new = array_3.reshape(3,3)
print(new)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#TAsk3
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#Task4
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array:", random_array)
print("Mean of the array:", mean_value)




Random array: [0.36892735 0.54745702 0.3082596  0.33210107 0.56717426 0.95776365
 0.35926706 0.11862839 0.05514417 0.98766619 0.85896113 0.70613486
 0.8099849  0.78932579 0.68932972 0.44199053 0.70587339 0.117199
 0.1374111  0.38469694 0.56664095 0.94558472 0.79844148 0.62176324
 0.31871908 0.32974743 0.62968867 0.48134597 0.83768365 0.40709793]
Mean of the array: 0.5393336412841225


In [11]:
#Task5
import numpy as np
random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[0.46953838 0.0257005  0.40897827 0.17994132 0.56345878 0.05674834
  0.46505494 0.09328917 0.25052673 0.8928302 ]
 [0.39830449 0.19971708 0.45645238 0.60093358 0.56358476 0.77297142
  0.45763463 0.89314435 0.81622764 0.17560089]
 [0.22343241 0.17346003 0.08672353 0.71219462 0.32522087 0.6687749
  0.14489097 0.91868841 0.48741501 0.15019628]
 [0.3063566  0.77016812 0.36595879 0.42843988 0.17002524 0.59469145
  0.81425087 0.21831619 0.55696464 0.53835623]
 [0.96492504 0.7354155  0.14092309 0.47081803 0.57688692 0.40697815
  0.30580294 0.96538618 0.5271904  0.07571275]
 [0.28567374 0.05771866 0.74328653 0.77698681 0.06002395 0.75428692
  0.50113209 0.90603925 0.24477937 0.50557806]
 [0.64525829 0.71167754 0.66569294 0.72796883 0.8912001  0.07374349
  0.21185025 0.6915861  0.63447183 0.45192441]
 [0.29299071 0.8537105  0.95768891 0.37038393 0.11092872 0.15044258
  0.53063067 0.41748267 0.42615192 0.83240493]
 [0.73738018 0.51305997 0.9483712  0.08493796 0.38227026 0.61963551

In [12]:
#Task6
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#Task7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [35]:
#Task8
import numpy as np
array=np.ones((5,5))
#set the inner elements to 0
array[1:-1, 1:-1]=0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
#TAsk9
#Creating an 8** Numpy array filled with zeros and setting alternate elements to 1 to create a checkerboard pattern
array=np.zeros((8,8) ,dtype=int)
#Setting alternate rows starting from the second row with alternate columns to 1
array[1::2, ::2]=1
#Setting alternate rows starting from the first row with alternate columns to 1
array[::2, 1::2]=1
print(array)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem2

In [15]:

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [26]:
# Task-1
add = x + y
add2 = w + v
print("Addition1:\n", add)
print("Addition2:\n", add2)

Addition1:
 [[ 6  8]
 [10 13]]
Addition2:
 [20 22]


In [27]:
#Task2
sub = x-y
sub2= w-v
print("Subtraction1:\n", sub)
print("Subtraction2:\n", sub2)

Subtraction1:
 [[-4 -4]
 [-4 -3]]
Subtraction2:
 [2 2]


In [28]:
#Task3
new_x = x*2
new_y = y*3
new_v = v*4
new_w = w*5
print("X:\n", new_x)
print("Y:\n", new_y)
print("V:\n", new_v)
print("Z:\n", new_w)

X:
 [[ 2  4]
 [ 6 10]]
Y:
 [[15 18]
 [21 24]]
V:
 [36 40]
Z:
 [55 60]


In [29]:
#Task-4
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
sqrt_x = np.sqrt(x)
sqrt_y = np.sqrt(y)
sqrt_v = np.sqrt(v)
sqrt_w = np.sqrt(w)

print("Square root of x:\n", sqrt_x)
print("Square root of y:\n", sqrt_y)
print("Square root of v:\n", sqrt_v)
print("Square root of w:\n", sqrt_w)

Square root of x:
 [[1.         1.41421356]
 [1.73205081 2.23606798]]
Square root of y:
 [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
Square root of v:
 [3.         3.16227766]
Square root of w:
 [3.31662479 3.46410162]


In [30]:
#Task-5
dot_v_w=np.dot(v,w)
dot_x_v=np.dot(x,v)
dot_x_y=np.dot(x,y)
print("Dot product of v and w arrays:\n", dot_v_w)
print("Dot product of x and v arrays:\n", dot_x_v)
print("Dot product of x and y arrays:\n", dot_x_y)

Dot product of v and w arrays:
 219
Dot product of x and v arrays:
 [29 77]
Dot product of x and y arrays:
 [[19 22]
 [50 58]]


In [31]:
#Task-6

array_v_w = np.stack((v, w), axis=0)
print("Stacked v and w arrays:\n", array_v_w)


array_x_y = np.vstack((x, y))
print("Stacked x and y arrays (vertically):\n", array_x_y)

Stacked v and w arrays:
 [[ 9 10]
 [11 12]]
Stacked x and y arrays (vertically):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


Problem 4

In [32]:
#Task-1
A = np.array([[3, 4], [7, 8]])


A_inv = np.linalg.inv(A)


result = np.dot(A, A_inv)

print("A * A_inv = \n", result)


I = np.eye(2)

print("\nIdentity matrix I:\n", I)
print("\nIs A * A_inv approximately equal to I? ", np.allclose(result, I))

A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix I:
 [[1. 0.]
 [0. 1.]]

Is A * A_inv approximately equal to I?  True


In [33]:
#task-2
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute the product AB
AB = np.dot(A, B)

# Compute the product BA
BA = np.dot(B, A)

# Print the results
print("AB = \n", AB)
print("\nBA = \n", BA)

# Verify if AB is equal to BA
print("\nIs AB equal to BA? ", np.array_equal(AB, BA))

AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]

Is AB equal to BA?  False


In [51]:
#TAsk3
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T,A.T)
print("\n(AB)^T:")
print(AB_transpose)
print("\nB^T * A^T:")
print(BT_AT)

#Solve the system of linear equation using Inverse methods.
#Represent the equations in matrix form AX = B
A_linear = np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B_linear = np.array([-1,-3,9]).reshape(-1,1)

#Solve for x using inverse method
A_linear_inv = np.linalg.inv(A_linear)
X_solution = np.dot(A_linear_inv,B_linear)
print("\nSolution to the system of linear equations:")
print(X_solution)


(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T:
[[23 51]
 [13 29]]

Solution to the system of linear equations:
[[ 2.]
 [ 1.]
 [-2.]]


In [41]:
import time
import numpy as np

# 1. Element-wise Addition
size = 1_000_000

# Python Lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
start = time.time()
result_list_add = [list1[i] + list2[i] for i in range(size)]
time_list_add = time.time() - start

# Numpy Arrays
array1 = np.arange(size)
array2 = np.arange(size)
start = time.time()
result_array_add = array1 + array2
time_array_add = time.time() - start

# 2. Element-wise Multiplication

# Python Lists
start = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(size)]
time_list_mul = time.time() - start

# Numpy Arrays
start = time.time()
result_array_mul = array1 * array2
time_array_mul = time.time() - start

# 3. Dot Product

# Python Lists
start = time.time()
result_list_dot = sum(list1[i] * list2[i] for i in range(size))
time_list_dot = time.time() - start

# Numpy Arrays
start = time.time()
result_array_dot = np.dot(array1, array2)
time_array_dot = time.time() - start

# 4. Matrix Multiplication
matrix_size = 300  # Smaller size for Python lists
matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

# Python Lists - Matrix Multiplication
start = time.time()
result_matrix_mul = [
    [sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)]
    for i in range(matrix_size)
]
time_matrix_mul = time.time() - start

# NumPy Arrays - Matrix Multiplication
matrix_array1 = np.arange(1000**2).reshape(1000, 1000)
matrix_array2 = np.arange(1000**2).reshape(1000, 1000)
start = time.time()
result_array_matrix_mul = np.dot(matrix_array1, matrix_array2)
time_array_matrix_mul = time.time() - start

# Results
print(f"Element-wise Addition: Python Lists: {time_list_add:.6f}s, NumPy Arrays: {time_array_add:.6f}s")
print(f"Element-wise Multiplication: Python Lists: {time_list_mul:.6f}s, NumPy Arrays: {time_array_mul:.6f}s")
print(f"Dot Product: Python Lists: {time_list_dot:.6f}s, NumPy Arrays: {time_array_dot:.6f}s")
print(f"Matrix Multiplication: Python Lists (300x300): {time_matrix_mul:.6f}s, NumPy Arrays (1000x1000): {time_array_matrix_mul:.6f}s")

Element-wise Addition: Python Lists: 0.297483s, NumPy Arrays: 0.005657s
Element-wise Multiplication: Python Lists: 0.310408s, NumPy Arrays: 0.006266s
Dot Product: Python Lists: 0.273698s, NumPy Arrays: 0.002171s
Matrix Multiplication: Python Lists (300x300): 5.304622s, NumPy Arrays (1000x1000): 1.733263s
